// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"Go_Gingonic_Server/bank"
	"github.com/jinzhu/gorm"
)

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func initBankAPI(db *gorm.DB) bank.BankAPI {
	bankRepository := bank.ProvideBankRepostiory(db)
	bankService := bank.ProvideBankService(bankRepository)
	bankAPI := bank.ProvideBankAPI(bankService)
	return bankAPI
}
