// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package router

import (
	"Go_Gingonic_Server/accounts"
	"Go_Gingonic_Server/bank"
	"Go_Gingonic_Server/utils"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func initBankAPI(db *gorm.DB) bank.BankAPI {
	bankRepository := bank.ProvideBankRepostiory(db)
	bankService := bank.ProvideBankService(bankRepository)
	bankAPI := bank.ProvideBankAPI(bankService)
	return bankAPI
}

func initAccountsAPI(db *gorm.DB, jwt *utils.JWT) accounts.AccountAPI {
	accountsRepository := accounts.ProvideAccountsRepostiory(db)
	accountService := accounts.ProvideAccountService(accountsRepository)
	accountAPI := accounts.ProvideAccountAPI(accountService, jwt)
	return accountAPI
}
