// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"Go_Gingonic_Server/admin"
	"github.com/jinzhu/gorm"
)

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func InitAdminAPI(db *gorm.DB) admin.Api {
	repository := admin.ProvideAdminRepostiory(db)
	service := admin.ProvideAdminService(repository)
	api := admin.ProvideAdminApi(service)
	return api
}
