// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package router

import (
	"Go_Gingonic_Server/topics"
	"Go_Gingonic_Server/utils"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func initTopicsAPI(db *gorm.DB, jwt *utils.JWT) topics.TopicAPI {
	topicRepository := topics.ProvideTopicRepostiory(db)
	topicService := topics.ProvideTopicService(topicRepository)
	topicAPI := topics.ProvideTopicAPI(topicService, jwt)
	return topicAPI
}
