// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"Go_Gingonic_Redis/forum"
	"Go_Gingonic_Redis/redis_server"
	"github.com/go-redis/redis"
)

// Injectors from wire.go:

func initTopicsAPI(redis2 *redis.Client, redisApi *redis_server.MainAPi) forums.CacheServerAPI {
	cacheServerAPI := forums.ProvideCacheAPI(redis2, redisApi)
	return cacheServerAPI
}
